import { LiquorCategory } from '../types';

export const SHOT_ML = 44.36; // 1.5 US fl oz

export const BOTTLE_SIZE_PRESETS = [375, 750, 1000, 1750]; // mL

export const CATEGORY_COLORS: Record<LiquorCategory, string> = {
  vodka:            '#A8D8EA',
  whiskey:          '#C8860A',
  bourbon:          '#B85C00',
  scotch:           '#8B7536',
  irish_whiskey:    '#D4A017',
  canadian_whiskey: '#E8C97A',
  rum:              '#4A1C00',
  gin:              '#A8D5A2',
  tequila:          '#F0C040',
  brandy:           '#7B1C3E',
  other:            '#7B5EA7',
};

export const LIQUOR_BRANDS: Array<{ brand: string; category: LiquorCategory }> = [
  // vodka
  { brand: 'Grey Goose', category: 'vodka' },
  { brand: 'Absolut', category: 'vodka' },
  { brand: 'Belvedere', category: 'vodka' },
  { brand: "Tito's", category: 'vodka' },
  { brand: 'Ketel One', category: 'vodka' },
  { brand: 'Smirnoff', category: 'vodka' },
  { brand: 'Stolichnaya', category: 'vodka' },
  { brand: 'Ciroc', category: 'vodka' },
  { brand: 'Skyy', category: 'vodka' },
  { brand: 'New Amsterdam', category: 'vodka' },
  { brand: 'Pinnacle', category: 'vodka' },
  { brand: 'Finlandia', category: 'vodka' },
  { brand: 'Chopin', category: 'vodka' },
  { brand: 'Żubrówka', category: 'vodka' },
  { brand: 'Russian Standard', category: 'vodka' },
  { brand: 'Imperia', category: 'vodka' },
  { brand: 'Reyka', category: 'vodka' },
  { brand: 'Deep Eddy', category: 'vodka' },
  { brand: 'Wheatley', category: 'vodka' },
  { brand: 'Prairie', category: 'vodka' },
  // whiskey
  { brand: "Jack Daniel's", category: 'whiskey' },
  { brand: "Jack Daniel's Single Barrel", category: 'whiskey' },
  { brand: 'Johnnie Walker Black', category: 'whiskey' },
  { brand: 'Johnnie Walker Red', category: 'whiskey' },
  { brand: 'Johnnie Walker Blue', category: 'whiskey' },
  { brand: 'Johnnie Walker Gold', category: 'whiskey' },
  { brand: 'Johnnie Walker Green', category: 'whiskey' },
  { brand: "Seagram's 7", category: 'whiskey' },
  { brand: "Dewar's White Label", category: 'whiskey' },
  { brand: "Dewar's 12", category: 'whiskey' },
  { brand: 'Black Velvet', category: 'whiskey' },
  { brand: 'Evan Williams', category: 'whiskey' },
  // bourbon
  { brand: "Maker's Mark", category: 'bourbon' },
  { brand: "Maker's 46", category: 'bourbon' },
  { brand: 'Woodford Reserve', category: 'bourbon' },
  { brand: 'Woodford Reserve Double Oaked', category: 'bourbon' },
  { brand: 'Buffalo Trace', category: 'bourbon' },
  { brand: 'Bulleit', category: 'bourbon' },
  { brand: 'Jim Beam', category: 'bourbon' },
  { brand: 'Jim Beam Black', category: 'bourbon' },
  { brand: 'Knob Creek', category: 'bourbon' },
  { brand: 'Knob Creek Single Barrel', category: 'bourbon' },
  { brand: "Basil Hayden's", category: 'bourbon' },
  { brand: "Booker's", category: 'bourbon' },
  { brand: "Baker's", category: 'bourbon' },
  { brand: 'Four Roses', category: 'bourbon' },
  { brand: 'Four Roses Single Barrel', category: 'bourbon' },
  { brand: 'Wild Turkey 101', category: 'bourbon' },
  { brand: 'Wild Turkey Rare Breed', category: 'bourbon' },
  { brand: "Russell's Reserve", category: 'bourbon' },
  { brand: 'Eagle Rare', category: 'bourbon' },
  { brand: "Blanton's", category: 'bourbon' },
  { brand: 'Pappy Van Winkle 15', category: 'bourbon' },
  { brand: 'Pappy Van Winkle 20', category: 'bourbon' },
  { brand: 'Pappy Van Winkle 23', category: 'bourbon' },
  { brand: 'W.L. Weller', category: 'bourbon' },
  { brand: 'Elijah Craig', category: 'bourbon' },
  { brand: 'Elijah Craig Barrel Proof', category: 'bourbon' },
  { brand: 'Heaven Hill', category: 'bourbon' },
  { brand: 'Old Forester', category: 'bourbon' },
  { brand: 'Old Forester 1920', category: 'bourbon' },
  { brand: 'Larceny', category: 'bourbon' },
  { brand: "Angel's Envy", category: 'bourbon' },
  { brand: "Jefferson's", category: 'bourbon' },
  { brand: "Michter's", category: 'bourbon' },
  { brand: 'Redemption', category: 'bourbon' },
  { brand: 'High West American Prairie', category: 'bourbon' },
  { brand: 'Wilderness Trail', category: 'bourbon' },
  { brand: 'New Riff', category: 'bourbon' },
  { brand: 'Rabbit Hole', category: 'bourbon' },
  // scotch
  { brand: 'Glenfiddich 12', category: 'scotch' },
  { brand: 'Glenfiddich 15', category: 'scotch' },
  { brand: 'Glenfiddich 18', category: 'scotch' },
  { brand: 'Glenfiddich 21', category: 'scotch' },
  { brand: 'Macallan 12', category: 'scotch' },
  { brand: 'Macallan 15', category: 'scotch' },
  { brand: 'Macallan 18', category: 'scotch' },
  { brand: 'Macallan Double Cask', category: 'scotch' },
  { brand: 'Laphroaig 10', category: 'scotch' },
  { brand: 'Laphroaig Quarter Cask', category: 'scotch' },
  { brand: 'Balvenie 12 DoubleWood', category: 'scotch' },
  { brand: 'Balvenie 14 Caribbean Cask', category: 'scotch' },
  { brand: 'Balvenie 21 PortWood', category: 'scotch' },
  { brand: 'Glenlivet 12', category: 'scotch' },
  { brand: 'Glenlivet 15', category: 'scotch' },
  { brand: 'Glenlivet 18', category: 'scotch' },
  { brand: 'Glenmorangie 10', category: 'scotch' },
  { brand: 'Glenmorangie Lasanta', category: 'scotch' },
  { brand: 'Glenmorangie Quinta Ruban', category: 'scotch' },
  { brand: 'Oban 14', category: 'scotch' },
  { brand: 'Dalmore 12', category: 'scotch' },
  { brand: 'Dalmore 15', category: 'scotch' },
  { brand: 'Highland Park 12', category: 'scotch' },
  { brand: 'Highland Park 18', category: 'scotch' },
  { brand: 'Ardbeg 10', category: 'scotch' },
  { brand: 'Ardbeg Uigeadail', category: 'scotch' },
  { brand: 'Bowmore 12', category: 'scotch' },
  { brand: 'Bruichladdich Classic Laddie', category: 'scotch' },
  { brand: 'Caol Ila 12', category: 'scotch' },
  { brand: 'Springbank 10', category: 'scotch' },
  { brand: 'Talisker 10', category: 'scotch' },
  { brand: 'Lagavulin 16', category: 'scotch' },
  { brand: 'Lagavulin 8', category: 'scotch' },
  { brand: 'Auchentoshan Three Wood', category: 'scotch' },
  { brand: 'GlenDronach 12', category: 'scotch' },
  { brand: 'Aberlour 12', category: 'scotch' },
  { brand: "Aberlour A'bunadh", category: 'scotch' },
  { brand: 'Craigellachie 13', category: 'scotch' },
  { brand: 'Benriach 10', category: 'scotch' },
  // irish_whiskey
  { brand: 'Jameson', category: 'irish_whiskey' },
  { brand: 'Jameson Black Barrel', category: 'irish_whiskey' },
  { brand: 'Jameson Caskmates', category: 'irish_whiskey' },
  { brand: 'Bushmills', category: 'irish_whiskey' },
  { brand: 'Bushmills Black Bush', category: 'irish_whiskey' },
  { brand: 'Bushmills 10', category: 'irish_whiskey' },
  { brand: 'Redbreast 12', category: 'irish_whiskey' },
  { brand: 'Redbreast 15', category: 'irish_whiskey' },
  { brand: 'Redbreast Lustau', category: 'irish_whiskey' },
  { brand: 'Tullamore D.E.W.', category: 'irish_whiskey' },
  { brand: 'Tullamore D.E.W. 14', category: 'irish_whiskey' },
  { brand: 'Powers', category: 'irish_whiskey' },
  { brand: "Powers John's Lane", category: 'irish_whiskey' },
  { brand: 'Green Spot', category: 'irish_whiskey' },
  { brand: 'Yellow Spot', category: 'irish_whiskey' },
  { brand: 'Teeling Small Batch', category: 'irish_whiskey' },
  { brand: 'Teeling Single Grain', category: 'irish_whiskey' },
  { brand: 'Teeling Single Malt', category: 'irish_whiskey' },
  { brand: 'Slane', category: 'irish_whiskey' },
  { brand: 'Connemara', category: 'irish_whiskey' },
  { brand: 'Knappogue Castle', category: 'irish_whiskey' },
  { brand: 'Tyrconnell', category: 'irish_whiskey' },
  { brand: 'Kilbeggan', category: 'irish_whiskey' },
  { brand: "Writers' Tears", category: 'irish_whiskey' },
  { brand: 'Midleton Very Rare', category: 'irish_whiskey' },
  // canadian_whiskey
  { brand: 'Crown Royal', category: 'canadian_whiskey' },
  { brand: 'Crown Royal Apple', category: 'canadian_whiskey' },
  { brand: 'Crown Royal Peach', category: 'canadian_whiskey' },
  { brand: 'Crown Royal XR', category: 'canadian_whiskey' },
  { brand: 'Canadian Club', category: 'canadian_whiskey' },
  { brand: 'Canadian Club 12', category: 'canadian_whiskey' },
  { brand: 'Forty Creek', category: 'canadian_whiskey' },
  { brand: 'Forty Creek Confederation Oak', category: 'canadian_whiskey' },
  { brand: 'Pendleton', category: 'canadian_whiskey' },
  { brand: 'Pendleton 1910', category: 'canadian_whiskey' },
  { brand: 'Lot 40', category: 'canadian_whiskey' },
  { brand: 'Pike Creek', category: 'canadian_whiskey' },
  { brand: 'Gooderham & Worts', category: 'canadian_whiskey' },
  { brand: "J.P. Wiser's", category: 'canadian_whiskey' },
  { brand: "Wiser's 18", category: 'canadian_whiskey' },
  { brand: 'Alberta Premium', category: 'canadian_whiskey' },
  { brand: 'Alberta Premium Cask Strength', category: 'canadian_whiskey' },
  { brand: 'Caribou Crossing', category: 'canadian_whiskey' },
  // rum
  { brand: 'Bacardi Superior', category: 'rum' },
  { brand: 'Bacardi Gold', category: 'rum' },
  { brand: 'Bacardi 8', category: 'rum' },
  { brand: 'Bacardi Oakheart', category: 'rum' },
  { brand: 'Captain Morgan Original', category: 'rum' },
  { brand: 'Captain Morgan Black', category: 'rum' },
  { brand: 'Captain Morgan 100', category: 'rum' },
  { brand: 'Havana Club 3', category: 'rum' },
  { brand: 'Havana Club 7', category: 'rum' },
  { brand: 'Mount Gay Eclipse', category: 'rum' },
  { brand: 'Mount Gay XO', category: 'rum' },
  { brand: 'Diplomatico Reserva Exclusiva', category: 'rum' },
  { brand: 'Diplomatico Planas', category: 'rum' },
  { brand: 'Appleton Estate', category: 'rum' },
  { brand: 'Appleton Estate 12', category: 'rum' },
  { brand: 'Appleton Estate 21', category: 'rum' },
  { brand: 'Plantation 3 Stars', category: 'rum' },
  { brand: 'Plantation Original Dark', category: 'rum' },
  { brand: 'Plantation XO', category: 'rum' },
  { brand: 'Ron Zacapa 23', category: 'rum' },
  { brand: 'Ron Zacapa XO', category: 'rum' },
  { brand: 'Flor de Caña 7', category: 'rum' },
  { brand: 'Flor de Caña 12', category: 'rum' },
  { brand: 'Flor de Caña 18', category: 'rum' },
  { brand: 'El Dorado 12', category: 'rum' },
  { brand: 'El Dorado 15', category: 'rum' },
  { brand: "Gosling's Black Seal", category: 'rum' },
  { brand: "Myers's Dark", category: 'rum' },
  { brand: 'Kraken', category: 'rum' },
  { brand: 'Sailor Jerry', category: 'rum' },
  { brand: 'Malibu', category: 'rum' },
  { brand: 'Angostura 1919', category: 'rum' },
  { brand: 'Angostura 7', category: 'rum' },
  { brand: 'Brugal 1888', category: 'rum' },
  { brand: 'Don Q Cristal', category: 'rum' },
  // gin
  { brand: "Hendrick's", category: 'gin' },
  { brand: "Hendrick's Orbium", category: 'gin' },
  { brand: 'Tanqueray', category: 'gin' },
  { brand: 'Tanqueray No. Ten', category: 'gin' },
  { brand: 'Tanqueray Rangpur', category: 'gin' },
  { brand: 'Bombay Sapphire', category: 'gin' },
  { brand: 'Bombay Sapphire East', category: 'gin' },
  { brand: 'Beefeater', category: 'gin' },
  { brand: 'Beefeater 24', category: 'gin' },
  { brand: 'The Botanist', category: 'gin' },
  { brand: 'Monkey 47', category: 'gin' },
  { brand: 'Aviation', category: 'gin' },
  { brand: 'Roku', category: 'gin' },
  { brand: 'Sipsmith', category: 'gin' },
  { brand: 'Sipsmith VJOP', category: 'gin' },
  { brand: 'Malfy Con Limone', category: 'gin' },
  { brand: 'Malfy Con Arancia', category: 'gin' },
  { brand: 'Malfy Originale', category: 'gin' },
  { brand: 'Empress 1908', category: 'gin' },
  { brand: 'St. George Terroir', category: 'gin' },
  { brand: 'St. George Botanivore', category: 'gin' },
  { brand: "Nolet's Silver", category: 'gin' },
  { brand: 'Plymouth', category: 'gin' },
  { brand: "Gordon's", category: 'gin' },
  { brand: "Seagram's Extra Dry", category: 'gin' },
  { brand: 'Drumshanbo Gunpowder', category: 'gin' },
  { brand: "Hayman's Old Tom", category: 'gin' },
  { brand: 'Citadelle', category: 'gin' },
  { brand: 'Bluecoat', category: 'gin' },
  // tequila
  { brand: 'Patrón Silver', category: 'tequila' },
  { brand: 'Patrón Reposado', category: 'tequila' },
  { brand: 'Patrón Añejo', category: 'tequila' },
  { brand: 'Patrón Extra Añejo', category: 'tequila' },
  { brand: 'Don Julio Blanco', category: 'tequila' },
  { brand: 'Don Julio Reposado', category: 'tequila' },
  { brand: 'Don Julio Añejo', category: 'tequila' },
  { brand: 'Don Julio 1942', category: 'tequila' },
  { brand: 'Don Julio 70', category: 'tequila' },
  { brand: 'Casamigos Blanco', category: 'tequila' },
  { brand: 'Casamigos Reposado', category: 'tequila' },
  { brand: 'Casamigos Añejo', category: 'tequila' },
  { brand: 'Jose Cuervo Especial', category: 'tequila' },
  { brand: 'Jose Cuervo Tradicional', category: 'tequila' },
  { brand: 'Espolòn Blanco', category: 'tequila' },
  { brand: 'Espolòn Reposado', category: 'tequila' },
  { brand: 'Herradura Silver', category: 'tequila' },
  { brand: 'Herradura Reposado', category: 'tequila' },
  { brand: 'Herradura Añejo', category: 'tequila' },
  { brand: 'El Jimador Blanco', category: 'tequila' },
  { brand: 'El Jimador Reposado', category: 'tequila' },
  { brand: 'Olmeca Altos Plata', category: 'tequila' },
  { brand: 'Olmeca Altos Reposado', category: 'tequila' },
  { brand: 'Clase Azul Reposado', category: 'tequila' },
  { brand: 'Clase Azul Añejo', category: 'tequila' },
  { brand: 'Fortaleza Blanco', category: 'tequila' },
  { brand: 'Fortaleza Reposado', category: 'tequila' },
  { brand: 'Fortaleza Añejo', category: 'tequila' },
  { brand: 'Siete Leguas Blanco', category: 'tequila' },
  { brand: 'G4 Blanco', category: 'tequila' },
  { brand: 'Tequila Ocho Plata', category: 'tequila' },
  { brand: 'Arette Blanco', category: 'tequila' },
  { brand: 'Tapatio Blanco', category: 'tequila' },
  { brand: '1800 Silver', category: 'tequila' },
  { brand: '1800 Reposado', category: 'tequila' },
  { brand: '1800 Añejo', category: 'tequila' },
  { brand: 'Hornitos Plata', category: 'tequila' },
  { brand: 'Sauza Blue Silver', category: 'tequila' },
  // brandy
  { brand: 'Hennessy VS', category: 'brandy' },
  { brand: 'Hennessy VSOP', category: 'brandy' },
  { brand: 'Hennessy XO', category: 'brandy' },
  { brand: 'Rémy Martin VSOP', category: 'brandy' },
  { brand: 'Rémy Martin XO', category: 'brandy' },
  { brand: 'Rémy Martin 1738', category: 'brandy' },
  { brand: 'Courvoisier VS', category: 'brandy' },
  { brand: 'Courvoisier VSOP', category: 'brandy' },
  { brand: 'Courvoisier XO', category: 'brandy' },
  { brand: 'Martell VS', category: 'brandy' },
  { brand: 'Martell VSOP', category: 'brandy' },
  { brand: 'Martell Cordon Bleu', category: 'brandy' },
  { brand: 'E&J VS', category: 'brandy' },
  { brand: 'E&J VSOP', category: 'brandy' },
  { brand: 'E&J XO', category: 'brandy' },
  { brand: 'Paul Masson VSOP', category: 'brandy' },
  { brand: 'Korbel', category: 'brandy' },
  { brand: 'Christian Brothers', category: 'brandy' },
  { brand: 'Torres 10', category: 'brandy' },
  { brand: 'Torres 20', category: 'brandy' },
  { brand: 'Calvados Père Magloire', category: 'brandy' },
  { brand: 'Armagnac Delord', category: 'brandy' },
  { brand: 'Armagnac Tariquet', category: 'brandy' },
  { brand: 'Pisco Portón', category: 'brandy' },
  { brand: 'Pisco Capel', category: 'brandy' },
];
