import { Amplify } from 'aws-amplify';

// amplifyconfiguration.json is generated by infra/scripts/generate-amplify-config.js
// after running `cdk deploy --outputs-file cdk-outputs.json`
let amplifyConfig: Record<string, unknown> = {};
try {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  amplifyConfig = require('../../amplifyconfiguration.json');
} catch {
  console.warn('amplifyconfiguration.json not found. Run the CDK deploy script first.');
}

export function configureAmplify(): void {
  if (Object.keys(amplifyConfig).length > 0) {
    Amplify.configure(amplifyConfig);
  }
}
